In [1]:
import importlib
import d20_data_preprocess
importlib.reload(d20_data_preprocess)
from d20_data_preprocess.eda import *
from d20_data_preprocess.preprocessing import *

In [2]:
df=pd.read_csv('ford.csv')

Preprocessing:
Missing values,
Incorrect data types,
Different scales,
Duplicate records,
Unwanted columns,
Different DataFrames,
Incorrect formats,

In [3]:
df.head()

     model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0   Fiesta  2017  12000    Automatic    15944   Petrol  150  57.7         1.0
1    Focus  2018  14000       Manual     9083   Petrol  150  57.7         1.0
2    Focus  2017  13000       Manual    12456   Petrol  150  57.7         1.0
3   Fiesta  2019  17500       Manual    10460   Petrol  145  40.3         1.5
4   Fiesta  2019  16500    Automatic     1482   Petrol  145  48.7         1.0

In [ ]:
import pandas as pd
from tests.dptest import *

In [2]:
df=pd.read_csv('ford.csv')

In [7]:
EDA(df)

In [3]:
df_copy=df.copy()

In [4]:
df_copy.head()

     model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0   Fiesta  2017  12000    Automatic    15944   Petrol  150  57.7         1.0
1    Focus  2018  14000       Manual     9083   Petrol  150  57.7         1.0
2    Focus  2017  13000       Manual    12456   Petrol  150  57.7         1.0
3   Fiesta  2019  17500       Manual    10460   Petrol  145  40.3         1.5
4   Fiesta  2019  16500    Automatic     1482   Petrol  145  48.7         1.0

In [5]:
df_copy=onehotenc(df_copy,'transmission')

In [6]:
df_copy.head()

,model,year,price,mileage,fuelType,tax,mpg,engineSize,transmission_Manual,transmission_Semi-Auto
0,Fiesta,2017,12000,15944,Petrol,150,57.7,1.0,False,False
1,Focus,2018,14000,9083,Petrol,150,57.7,1.0,True,False
2,Focus,2017,13000,12456,Petrol,150,57.7,1.0,True,False
3,Fiesta,2019,17500,10460,Petrol,145,40.3,1.5,True,False
4,Fiesta,2019,16500,1482,Petrol,145,48.7,1.0,False,False

In [7]:
levelenc(df_copy,'transmission_Manual')
levelenc(df_copy,'transmission_Semi-Auto')

In [8]:
df_copy.head()

,model,year,price,mileage,fuelType,tax,mpg,engineSize,transmission_Manual,transmission_Semi-Auto
0,Fiesta,2017,12000,15944,Petrol,150,57.7,1.0,0,0
1,Focus,2018,14000,9083,Petrol,150,57.7,1.0,1,0
2,Focus,2017,13000,12456,Petrol,150,57.7,1.0,1,0
3,Fiesta,2019,17500,10460,Petrol,145,40.3,1.5,1,0
4,Fiesta,2019,16500,1482,Petrol,145,48.7,1.0,0,0

In [9]:
d20help()

============================================================
📊 COMPLETE DATA PREPROCESSING REFERENCE GUIDES 📊
============================================================

🔹 Data Cleaning & Structuring
---------------------------
  • df.info()                        -> Prints a summary of the DataFrame, including data types and non-null counts.
  • df.describe()                    -> Generates summary statistics like mean, median, and min/max for numerical columns.
  • df.isna().sum()                  -> Counts the total number of missing (NaN) values in each column.
  • df.dropna()                      -> Removes rows or columns that contain missing or null values.
  • df.fillna()                      -> Replaces missing or null values with a specified value, mean, or median.
  • df.drop_duplicates()             -> Removes duplicate rows to ensure every record is unique.
  • df.astype()                      -> Casts a column or Series to a specified data type (e.g., float to int).
  • df.rename()                      -> Alters column or row labels using a dictionary mapping.
  • df.drop()                        -> Removes specified rows or columns from the DataFrame.

🔹 Data Transformation & Scaling
-----------------------------
  • pd.get_dummies()                 -> Converts categorical text columns into one-hot encoded numerical variables.
  • df.apply()                       -> Applies a custom function or lambda expression along a DataFrame axis.
  • df.map()                         -> Maps values of a Series using a dictionary or function for label encoding.
  • StandardScaler().fit_transform() -> Standardises features by removing the mean and scaling to unit variance.
  • MinMaxScaler().fit_transform()   -> Rescales numerical features to a specified range, typically 0 to 1.
  • KBinsDiscretizer()               -> Bins continuous numerical variables into discrete, categorical intervals.

🔹 Reshaping & Combining Data
--------------------------
  • pd.concat()                      -> Combines multiple DataFrames or Series along a particular axis (rows or columns).
  • pd.merge()                       -> Joins two DataFrames together based on a shared key or index (SQL-style join).
  • df.groupby()                     -> Groups data by specific criteria to allow for aggregate calculations.
  • df.pivot()                       -> Reshapes data from a long format to a wide format based on column values.
  • df.melt()                        -> Unpivots a DataFrame from a wide format to a long format.

🔹 Advanced Feature Engineering
----------------------------
  • train_test_split()               -> Splits a dataset into random train and test subsets for model validation.
  • SimpleImputer()                  -> A scikit-learn transformer to handle missing data using mean, median, or mode.
  • OneHotEncoder()                  -> An ML-pipeline friendly scikit-learn transformer for encoding categorical features.
  • LabelEncoder()                   -> Encodes target labels with numerical values between 0 and n-1 classes.
  • PCA()                            -> Reduces dataset dimensionality by projecting data into a lower-dimensional space.

============================================================

In [2]:
d20help('transform')

-pd.get_dummies() -> Converts categorical text columns into one-hot encoded numerical variables.
-df.apply() -> Applies a custom function or lambda expression along a DataFrame axis.
-df.map()   -> Maps values of a Series using a dictionary or function for label encoding.
-StandardScaler().fit_transform() -> Standardises features by removing the mean and scaling to unit variance.
-MinMaxScaler().fit_transform() -> Rescales numerical features to a specified range, typically 0 to 1.
-KBinsDiscretizer() -> Bins continuous numerical variables into discrete, categorical intervals.

In [ ]:
import pandas as pd
from tests.dptest import *

In [4]:
df=pd.read_csv('ford.csv')

In [5]:
EDA(df)